-- Create tables here
CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    ACCOUNT_NUMBER VARCHAR(20),
    CITY VARCHAR(50)
);

CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    TRANSACTION_AMOUNT DECIMAL(10,2),
    STATUS VARCHAR(20),

    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE FRAUD_ALERT (
    ALERT_ID INT AUTO_INCREMENT PRIMARY KEY,
    TRANSACTION_ID INT,
    RISK_LEVEL VARCHAR(20),

    FOREIGN KEY (TRANSACTION_ID)
    REFERENCES TRANSACTIONS(TRANSACTION_ID)
);

CREATE TABLE fraud_data (
    Time FLOAT,
    Amount FLOAT,
    Class INT
);
