-- Insert sample data here
INSERT INTO CUSTOMER
(CUSTOMER_NAME, ACCOUNT_NUMBER, CITY)
VALUES
('Rahul Sharma', 'ACC1001', 'Mumbai'),
('Priya Verma', 'ACC1002', 'Delhi');

INSERT INTO TRANSACTIONS
(CUSTOMER_ID, TRANSACTION_AMOUNT, STATUS)
VALUES
(1, 2000, 'NORMAL'),
(2, 90000, 'NORMAL');
